/*
 * ADC_Cfg.h
 *
 * Created: 3/25/2022 10:44:34 AM
 *  Author: Yasser & Mahmoud
 */ 


#ifndef ADC_CFG_H_
#define ADC_CFG_H_

#define ADC_VOLTAGE_REFERENCE   ADC_VOLTAGE_REFERENCE_VCC
#define ADC_CHANNEL				ADC_CHANNEL_01
#define ADC_CONVERSION_TRIGGER  ADC_CONVERSION_AUTO_TRIGGER 
#define ADC_PRESCALER			ADC_PRESCALER_128
#define ADC_INTERRUPT_STATUS	ADC_INTERRUPT_DISABLED
#define ADC_ADJUST				ADC_RIGHT_ADJUST



#endif /* ADC_CFG_H_ */